### ISSUE TITLE
Add broadcast receivers - to auto restart our service

### ISSUE THREAD

**Issue by ButtersHub** [wix-incubator/rn-contact-tracing#10]
Our foreground service should continue to run on:
1. BOOT_COMPLETED - power off/on the device
2. MY_PACKAGE_REPLACED - upgrade of the app to new version
3. QUICKBOOT_POWERON - restart/reboot of the device

**Comment by EitanSchwartz** [comment]
Currently we receive serviceUUID & publicKey from JS layer when calling startBLEService(), where would these values come from when starting the service from the receiver?
-- Suggesting either BLEModule or BLEForegroundService will "Remember their last set uuid&pk..
Any thoughts?

**Comment by ButtersHub** [comment]
All the config, including the serviceUUID saved in persistence memory (shared-pref), pub_key be added there as well should.

**Comment by EitanSchwartz** [comment]
- setConfig() receives the uuid but not the publicKey. Do you want us to add it there?
- Currently advertise/scan receive pk/uuid, how would this config be received? We can have them override existing sPrefs config or these args. can be completely removed from these methods, how do you see it?

**Comment by ButtersHub** [comment]
1. I asked Kobi to add it, he will call it test_token (because it is relevant only for testing).
He already implemented the part that it is editable from the JS.
2. you right, the parameters from start advertise/scan/service should be removed the only param that supposed to be there is the config object that should be optional

**Comment by ButtersHub** [comment]
If you look [here](https://github.com/wix-incubator/rn-contact-tracing#summary ), i defined yesterday the API, so i removed all params except the config

**Comment by EitanSchwartz** [comment]
I'm missing info. (Incl. what's in the API documentation).

- Kobi will add publicKey to Config, but will name it "test_token"? What will be the publicKey for starting the foreground service in production?

**Comment by ButtersHub** [comment]
The API documentation is in the README - at the bottom - https://github.com/wix-incubator/rn-contact-tracing.

**Comment by ButtersHub** [comment]
in production instead test_token the key will be generated

**Comment by EitanSchwartz** [comment]
I'll try and explain:
<img width="738" alt="Screen Shot 2020-04-21 at 14 34 51" src="https://user-images.githubusercontent.com/43198730/79861605-52e56d80-83dd-11ea-8af3-1c367daf10aa.png">

**Comment by ButtersHub** [comment]
In general, BLEAdvertisingManager can be responsible for getting the _ServiceUUID_ & _test_token_ from the Config.

In production, BLEAdvertisingManager will get this token from the module that will generate the tokens.

Im not sure I understood you, call me :)
