### ISSUE TITLE
Error running in Android

### ISSUE THREAD

**Issue by mlopezfernandez** [wix-incubator/rn-contact-tracing#17]
I am testing this library for a COVID-19 related project. After installing it and trying to run the project in Android device returns the following error:

>Where:
>Build file '/home/mlopez/git/RapidApp/node_modules/rn-contact->tracing/android/build.gradle' line: 104

>What went wrong:
>A problem occurred configuring project ':rn-contact-tracing'.
> Cannot get property 'username' on null object`

I have noticed that in the package.json of the library an author is not specified but if you add it manually the app runs correctly. Am I doing something wrong?

**Comment by ButtersHub** [comment]
@mlopezfernandez did you fetch the code from NPM or Git?
Try to use version 0.0.3 from npm it should work

**Comment by tidusdavid** [comment]
I tried to npm install version 0.0.3 (latest) and I'm having the following issue when running my application:
![Screenshot_20200423-081844](https://user-images.githubusercontent.com/2531157/80065988-627ac880-853b-11ea-938f-b89a25705ae5.jpg)

**Comment by mlopezfernandez** [comment]
@ButtersHub I have installed version 0.0.3 through NPM, I previously had 0.0.2. Now the problem is the SpecialBle object as @tidusdavid says is null. ¿We are doing something wrong? ¿We have to link the library? Thanks!

**Comment by ButtersHub** [comment]
@mlopezfernandez the auto-linking is not working for some reason (ill take a look on this today), meanwhile you can link it manually: 
In your settings.gradle file add:
```
include ':rn-contact-tracing'
project(':rn-contact-tracing').projectDir = new File(rootProject.projectDir, '../node_modules/rn-contact-tracing/lib/android')
```
in app/build.gradle add this as a dependancy:
` implementation project(":rn-contact-tracing")`

and in your MainApplication.java class in the getPackages method add this:
`packages.add(new SpecialBlePackage());`

**Comment by ButtersHub** [comment]
@tidusdavid ill take a look on this today, thx

**Comment by tidusdavid** [comment]
@ButtersHub Thanks, I'm working with @mlopezfernandez  too so we are having the same issues. By the way, it is required also to `import com.wix.specialble.SpecialBlePackage;` inside the MainApplication.java.

Thanks again and we will test.

**Comment by mlopezfernandez** [comment]
@ButtersHub It works correctly, thank you very much for your work.
